import turtle as t
max = float(input("What is your maximum:  "))
min = float(input("What is your minimum:  "))
lower = float(input("What is your lower quartile:  "))
upper = float(input("What is your upper quartile:  "))
median = float(input("What is your median:  "))

t.screensize(1000, 1000, "white")
t.speed(0)
t.up()
t.goto(lower-upper, 0)
t.down()

t.lt(90)
t.fd(40)
t.bk(80)
t.fd(40)
t.rt(90)
t.fd(lower-min)
t.rt(90)
t.fd(40)
t.lt(90)
t.fd(upper-lower)
t.lt(90)
t.fd(80)
t.lt(90)
t.fd(upper-lower)
t.lt(90)
t.fd(80)
t.lt(90)
t.fd(median-lower)
t.lt(90)
t.fd(80)
t.rt(90)
t.fd(upper-median)
t.rt(90)
t.fd(40)
t.lt(90)
t.fd(max-upper)
t.lt(90)
t.fd(40)
t.bk(80)
